name: Deploy DotNet project to Azure Function App

on: [push]

env:
    AZURE_FUNCTIONAPP_NAME: "MLecture"
    AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
    DOTNET_VERSION: "8.x"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: "Checkout GitHub Action"
              uses: actions/checkout@v6.0.2

            - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
              uses: actions/setup-dotnet@v5.1.0
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: "Resolve Project Dependencies Using Dotnet"
              shell: bash
              run: |
                  pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
                  dotnet build --configuration Release --output ./output
                  popd

            - name: "Run Azure Functions Action"
              uses: Azure/functions-action@v1.5.3
              id: fa
              with:
                  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                  package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
                  publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
                  scm-do-build-during-deployment: false
                  enable-oryx-build: false